#FROM python:3.6
#FROM python:3.7
#FROM python:3.8
#FROM python:3.9
FROM python:3.10

WORKDIR ./

COPY . .

# Install Python dependencies which it runs pytest it needs
RUN pip install -U pip && \
      pip install -U pytest &&\
      pip install -U pytest-cov &&\
      pip install pytest-rerunfailures &&\
      pip install codecov &&\
      pip install mysql-connector-python &&\
      pip install -r dev-requirements.txt

CMD ["pytest"]

