from pyocean.parallel.operator import ParallelProcedure
from pyocean.parallel.strategy import ParallelStrategy, MultiProcessingStrategy
from pyocean.parallel.factory import ParallelSimpleFactory, ParallelPersistenceFactory
from pyocean.parallel.features import MultiProcessingQueueType
